{
  "hash": "c374201d87f0c814c8e28feda83e5d63",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Interactions and Nonlinear Relationships\ndate: today\ndate-format: long\nfooter: \"[IAFF 6501 Website](https://quant4ia.rocks/)\"\nlogo: images/iaff6501-logo.png\nformat:\n  revealjs:\n    theme: [simple, custom.scss]\n    transition: fade\n    slide-number: true\n    #multiplex: true\n    chalkboard: true\nexecute:\n  echo: true\n  message: false\n  warning: false\n  freeze: auto\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(tidymodels)\nlibrary(patchwork)\n#library(DT)\nlibrary(vdemdata)\n```\n:::\n\n\n## Oil Wealth and Democracy\n\nPolitical Resource Curse\n\n\n## Set up data: Use the year 2005\n\n\n::: {.cell}\n\n```{.r .cell-code}\noilData <- vdem %>% \n  filter(year == 2005) %>% \n  select(country_name, v2x_libdem, e_gdppc, v2cacamps, e_total_oil_income_pc, v2x_corr, v2pepwrgen, v2clgencl) %>% \n  mutate(lg_gdppc = log(e_gdppc))\n```\n:::\n\n\n## Distribution of Oil Wealth per Capita\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-11.1._files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n## Create a Dummy Variable for High Oil Wealth\n\n\n::: {.cell}\n\n```{.r .cell-code}\noilData <- oilData %>% \n  mutate(\n        oil = ifelse(e_total_oil_income_pc > 152, 1, 0),\n         oil = factor(oil, labels=c(\"No Oil Wealth\", \"Oil Wealth\"))\n        ) %>% \n  filter(oil == \"No Oil Wealth\" | oil == \"Oil Wealth\")\ntable(oilData$oil)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNo Oil Wealth    Oil Wealth \n          122            41 \n```\n\n\n:::\n:::\n\n\n## Democracy, GDP per Capita, and Oil Wealth\n\nHow should we interpret this graph?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-11.1._files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n\n## Model with Oil and GDP per Capita, No Interaction\n\nWhat is correct interpretation?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(v2x_libdem ~ lg_gdppc + oil, data = oilData) %>% \n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term          estimate std.error statistic  p.value\n  <chr>            <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)      0.160    0.0318      5.02 1.36e- 6\n2 lg_gdppc         0.152    0.0144     10.5  4.53e-20\n3 oilOil Wealth   -0.233    0.0395     -5.90 2.08e- 8\n```\n\n\n:::\n:::\n\n\n\n## Interaction Model\n\n- Does GDP per capita have a different relationship to democracy in Oil rich versus non-Oil rich countries?\n\n\n## Interaction Model\n\n\n- $Y_i = a + b_1 * GDPpc + b_2 * Oil + b_3 * GDPpc * Oil$\n\n. . .\n\n\n- $b_3 * GDPpc * OilWealth$ captures the interaction\n\n\n## Interaction Model: Interpretation\n\n\n- How should we interpret $a$?\n\n\n- $Y_i = a + b_1 * GDPpc + b_2 * Oil + b_3 * GDPpc * Oil$\n\n. . .\n\n\n- $a$ is predicted level of democracy where GDPpc = 0 and Oil Wealth = 0\n\n\n\n## Interaction Model: Interpretation\n\n- What happens if we set Oil Wealth to 0?\n\n- $Y_i = a + b_1 * GDPpc + b_2 * Oil + b_3 * GDPpc * Oil$\n\n- $Y_i = a + b_1 * GDPpc + b_2 * 0 + b_3 * GDPpc * 0$\n\n- $Y_i = a + b_1 * GDPpc$\n\n\n. . .\n\n\n- $b_1$ is the association between GDP per capita and democracy, **when oil wealth = 0**\n\n\n## Interaction Model: Interpretation\n\n- What happens if we set GDPpc to 0?\n\n- $Y_i = a + b_1 * GDPpc + b_2 * Oil + b_3 * GDPpc * Oil$\n\n- $Y_i = a + b_1 * 0 + b_2 * Oil + b_3 * Oil * 0$\n\n- $Y_i = a + b_2 * Oil$\n\n- $b_2$ is the association between oil and democracy, **when GDP per capita = 0**\n\n\n## Interaction Model: Interpretation\n\n- What happens if we set Oil Wealth to 1?\n\n- $Y_i = a + b_1 * GDPpc + b_2 * 1 + b_3 * GDPpc * 1$\n\n- Rearrange: $Y_i = a + (b_1 + b_3) * GDPpc + b_2 * 1$\n\n\n. . .\n\n- $b_1 + b_3$ is the association between GDP per capita and democracy, **when oil wealth = 1**\n\n\n## Run the Interaction Model\n\nWhat is correct interpretation of each coefficient?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(v2x_libdem ~ lg_gdppc*oil, data = oilData) %>% \n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                   estimate std.error statistic  p.value\n  <chr>                     <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)              0.138     0.0342     4.03  8.51e- 5\n2 lg_gdppc                 0.164     0.0160    10.2   3.25e-19\n3 oilOil Wealth           -0.0850    0.0951    -0.893 3.73e- 1\n4 lg_gdppc:oilOil Wealth  -0.0607    0.0355    -1.71  8.88e- 2\n```\n\n\n:::\n:::\n\n\n## Interpretation\n\n\n$\\hat{Y_i}$ = .138 + .164 * $GDPpc_i$ + (-0.085) * $Oil_i$ \n+ (-0.0607) * $GDPpc_i$ * $Oil_i$\n\n. . .\n\n- Relationship without oil: $0.164$\n\n- Relationship with oil: $0.164 + (-0.0607) = 0.164 -0.0607 = 0.1033$\n \n## Is this difference due to chance?\n\n- Does GDP have a lower relationship to democracy in oil rich countries?\n\n- Is 0.164 without oil different from 0.1033 with oil?\n\n. . .\n\n- What is the null hypothesis?  What is the alternative?\n\n## Is this difference due to chance?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(v2x_libdem ~ lg_gdppc*oil, data = oilData) %>% \n  tidy(conf.int=TRUE) %>% \n  filter(term == \"lg_gdppc:oilOil Wealth\") %>% \n  select(term, estimate, std.error, p.value, conf.low, conf.high) %>%   \n  mutate(across(where(is.numeric), round, 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  term                   estimate std.error p.value conf.low conf.high\n  <chr>                     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 lg_gdppc:oilOil Wealth   -0.061     0.035   0.089   -0.131     0.009\n```\n\n\n:::\n:::\n\n\n## Is this difference due to chance?\n\n\n- 95% Confidence Interval: [-0.131, 0.009]: mostly negative\n\n- p-value of interaction term: 0.089\n\n    - this is higher that 0.05, but close and remember that the cutoff is arbitrary\n\n\n## Your Turn: Oil Wealth and Women's Civil Liberties\n\n- V-Dem has a variable capturing respect for women's civil liberties -v2clgencl\n\n- How do GDP per capita and oil wealth relate to women's civil liberties?\n\n- First, use oilData to create a scatterplot that visualizes this relationship.\n\n- Second, fit an interaction model (oil X GDP per capita) predicting women's civil liberties\n\n- Interpret each of the coefficients and the intercept\n\n- What is your overall conclusion(s) from this model?\n\n\n## Your Turn: Oil Wealth and Women's Civil Liberties\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](week-11.1._files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n## Your Turn: Oil Wealth and Women's Civil Liberties\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(v2clgencl ~ lg_gdppc*oil, data = oilData) %>% \n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term                   estimate std.error statistic  p.value\n  <chr>                     <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)               0.489    0.167      2.93  3.87e- 3\n2 lg_gdppc                  0.548    0.0781     7.02  6.22e-11\n3 oilOil Wealth            -0.305    0.464     -0.657 5.12e- 1\n4 lg_gdppc:oilOil Wealth   -0.237    0.173     -1.37  1.73e- 1\n```\n\n\n:::\n:::\n",
    "supporting": [
      "week-11.1._files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}